spring:
  datasource:
    # 数据库连接URL，连接名为my-easy-blog的MySQL数据库
    # useSSL=false: 不使用SSL连接
    # serverTimezone=Asia/Shanghai: 设置服务器时区为上海
    # characterEncoding=utf8: 字符编码为UTF-8
    # allowPublicKeyRetrieval=true: 允许公钥检索
    url: jdbc:mysql://localhost:3306/my-easy-blog?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
    # MySQL驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源类型，使用Hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池名称
      pool-name: HikariCP
      # 连接池最大连接数
      maximum-pool-size: 20
      # 连接池最小空闲连接数
      minimum-idle: 5
      # 连接空闲超时时间(毫秒)
      idle-timeout: 300000
      # 连接最大生命周期(毫秒)
      max-lifetime: 1200000
      # 连接超时时间(毫秒)
      connection-timeout: 30000

# MyBatis配置
mybatis:
  # 配置别名包，实体类所在的包
  type-aliases-package: com.gb.myeasyblog.entity
  # Mapper XML文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换，数据库下划线字段自动映射到Java驼峰属性
    map-underscore-to-camel-case: true
    # 配置MyBatis日志实现，使用标准输出打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# PageHelper配置
pagehelper:
  helper-dialect: mysql

# application.yml
jwt:
  secret: "4K5v8y/B?E(H+MbPeShVmYq3s6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G-KaPdSgUk" # 至少32字符
  expiration: 86400000 # 24小时，单位毫秒
